$linkererrors="
# begin_generated_IBM_copyright_prolog                             
#                                                                  
# This is an automatically generated copyright prolog.             
# After initializing,  DO NOT MODIFY OR MOVE                       
# ================================================================ 
#                                                                  
# Licensed Materials - Property of IBM                             
#                                                                  
# Blue Gene/Q                                                      
#                                                                  
# (C) Copyright IBM Corp.  2010, 2012                              
#                                                                  
# US Government Users Restricted Rights -                          
# Use, duplication or disclosure restricted                        
# by GSA ADP Schedule Contract with IBM Corp.                      
#                                                                  
# This software is available to you under the                      
# Eclipse Public License (EPL).                                    
#                                                                  
# ================================================================ 
#                                                                  
# end_generated_IBM_copyright_prolog                               
syscalls.o:(.data.rel+0x0): undefined reference to `sc_restart_syscall'
syscalls.o:(.data.rel+0x10): undefined reference to `sc_fork'
syscalls.o:(.data.rel+0x18): undefined reference to `sc_read'
syscalls.o:(.data.rel+0x30): undefined reference to `sc_close'
syscalls.o:(.data.rel+0x38): undefined reference to `sc_waitpid'
syscalls.o:(.data.rel+0x40): undefined reference to `sc_creat'
syscalls.o:(.data.rel+0x48): undefined reference to `sc_link'
syscalls.o:(.data.rel+0x50): undefined reference to `sc_unlink'
syscalls.o:(.data.rel+0x58): undefined reference to `sc_execve'
syscalls.o:(.data.rel+0x60): undefined reference to `sc_chdir'
syscalls.o:(.data.rel+0x70): undefined reference to `sc_mknod'
syscalls.o:(.data.rel+0x78): undefined reference to `sc_chmod'
syscalls.o:(.data.rel+0x80): undefined reference to `sc_lchown'
syscalls.o:(.data.rel+0x88): undefined reference to `sc_break'
syscalls.o:(.data.rel+0x90): undefined reference to `sc_oldstat'
syscalls.o:(.data.rel+0x98): undefined reference to `sc_lseek'
syscalls.o:(.data.rel+0xa8): undefined reference to `sc_mount'
syscalls.o:(.data.rel+0xb0): undefined reference to `sc_umount'
syscalls.o:(.data.rel+0xc8): undefined reference to `sc_stime'
syscalls.o:(.data.rel+0xd0): undefined reference to `sc_ptrace'
syscalls.o:(.data.rel+0xd8): undefined reference to `sc_alarm'
syscalls.o:(.data.rel+0xe0): undefined reference to `sc_oldfstat'
syscalls.o:(.data.rel+0xe8): undefined reference to `sc_pause'
syscalls.o:(.data.rel+0xf0): undefined reference to `sc_utime'
syscalls.o:(.data.rel+0xf8): undefined reference to `sc_stty'
syscalls.o:(.data.rel+0x100): undefined reference to `sc_gtty'
syscalls.o:(.data.rel+0x108): undefined reference to `sc_access'
syscalls.o:(.data.rel+0x110): undefined reference to `sc_nice'
syscalls.o:(.data.rel+0x118): undefined reference to `sc_ftime'
syscalls.o:(.data.rel+0x120): undefined reference to `sc_sync'
syscalls.o:(.data.rel+0x128): undefined reference to `sc_kill'
syscalls.o:(.data.rel+0x130): undefined reference to `sc_rename'
syscalls.o:(.data.rel+0x138): undefined reference to `sc_mkdir'
syscalls.o:(.data.rel+0x140): undefined reference to `sc_rmdir'
syscalls.o:(.data.rel+0x148): undefined reference to `sc_dup'
syscalls.o:(.data.rel+0x150): undefined reference to `sc_pipe'
syscalls.o:(.data.rel+0x160): undefined reference to `sc_prof'
syscalls.o:(.data.rel+0x198): undefined reference to `sc_acct'
syscalls.o:(.data.rel+0x1a0): undefined reference to `sc_umount2'
syscalls.o:(.data.rel+0x1a8): undefined reference to `sc_lock'
syscalls.o:(.data.rel+0x1b8): undefined reference to `sc_fcntl'
syscalls.o:(.data.rel+0x1c0): undefined reference to `sc_mpx'
syscalls.o:(.data.rel+0x1c8): undefined reference to `sc_setpgid'
syscalls.o:(.data.rel+0x1d0): undefined reference to `sc_ulimit'
syscalls.o:(.data.rel+0x1d8): undefined reference to `sc_oldolduname'
syscalls.o:(.data.rel+0x1e0): undefined reference to `sc_umask'
syscalls.o:(.data.rel+0x1e8): undefined reference to `sc_chroot'
syscalls.o:(.data.rel+0x1f0): undefined reference to `sc_ustat'
syscalls.o:(.data.rel+0x1f8): undefined reference to `sc_dup2'
syscalls.o:(.data.rel+0x200): undefined reference to `sc_getppid'
syscalls.o:(.data.rel+0x208): undefined reference to `sc_getpgrp'
syscalls.o:(.data.rel+0x210): undefined reference to `sc_setsid'
syscalls.o:(.data.rel+0x218): undefined reference to `sc_sigaction'
syscalls.o:(.data.rel+0x220): undefined reference to `sc_sgetmask'
syscalls.o:(.data.rel+0x228): undefined reference to `sc_ssetmask'
syscalls.o:(.data.rel+0x230): undefined reference to `sc_setreuid'
syscalls.o:(.data.rel+0x238): undefined reference to `sc_setregid'
syscalls.o:(.data.rel+0x240): undefined reference to `sc_sigsuspend'
syscalls.o:(.data.rel+0x248): undefined reference to `sc_sigpending'
syscalls.o:(.data.rel+0x250): undefined reference to `sc_sethostname'
syscalls.o:(.data.rel+0x278): undefined reference to `sc_settimeofday'
syscalls.o:(.data.rel+0x280): undefined reference to `sc_getgroups'
syscalls.o:(.data.rel+0x288): undefined reference to `sc_setgroups'
syscalls.o:(.data.rel+0x290): undefined reference to `sc_select'
syscalls.o:(.data.rel+0x298): undefined reference to `sc_symlink'
syscalls.o:(.data.rel+0x2a0): undefined reference to `sc_oldlstat'
syscalls.o:(.data.rel+0x2a8): undefined reference to `sc_readlink'
syscalls.o:(.data.rel+0x2b0): undefined reference to `sc_uselib'
syscalls.o:(.data.rel+0x2b8): undefined reference to `sc_swapon'
syscalls.o:(.data.rel+0x2c0): undefined reference to `sc_reboot'
syscalls.o:(.data.rel+0x2c8): undefined reference to `sc_readdir'
syscalls.o:(.data.rel+0x2e0): undefined reference to `sc_truncate'
syscalls.o:(.data.rel+0x2f0): undefined reference to `sc_fchmod'
syscalls.o:(.data.rel+0x2f8): undefined reference to `sc_fchown'
syscalls.o:(.data.rel+0x300): undefined reference to `sc_getpriority'
syscalls.o:(.data.rel+0x308): undefined reference to `sc_setpriority'
syscalls.o:(.data.rel+0x310): undefined reference to `sc_profil'
syscalls.o:(.data.rel+0x318): undefined reference to `sc_statfs'
syscalls.o:(.data.rel+0x320): undefined reference to `sc_fstatfs'
syscalls.o:(.data.rel+0x328): undefined reference to `sc_ioperm'
syscalls.o:(.data.rel+0x330): undefined reference to `sc_socketcall'
syscalls.o:(.data.rel+0x338): undefined reference to `sc_syslog'
syscalls.o:(.data.rel+0x340): undefined reference to `sc_setitimer'
syscalls.o:(.data.rel+0x348): undefined reference to `sc_getitimer'
syscalls.o:(.data.rel+0x358): undefined reference to `sc_lstat'
syscalls.o:(.data.rel+0x368): undefined reference to `sc_olduname'
syscalls.o:(.data.rel+0x370): undefined reference to `sc_iopl'
syscalls.o:(.data.rel+0x378): undefined reference to `sc_vhangup'
syscalls.o:(.data.rel+0x380): undefined reference to `sc_idle'
syscalls.o:(.data.rel+0x388): undefined reference to `sc_vm86'
syscalls.o:(.data.rel+0x390): undefined reference to `sc_wait4'
syscalls.o:(.data.rel+0x398): undefined reference to `sc_swapoff'
syscalls.o:(.data.rel+0x3a0): undefined reference to `sc_sysinfo'
syscalls.o:(.data.rel+0x3a8): undefined reference to `sc_ipc'
syscalls.o:(.data.rel+0x3b0): undefined reference to `sc_fsync'
syscalls.o:(.data.rel+0x3b8): undefined reference to `sc_sigreturn'
syscalls.o:(.data.rel+0x3c8): undefined reference to `sc_setdomainname'
syscalls.o:(.data.rel+0x3d8): undefined reference to `sc_modify_ldt'
syscalls.o:(.data.rel+0x3e0): undefined reference to `sc_adjtimex'
syscalls.o:(.data.rel+0x3f0): undefined reference to `sc_sigprocmask'
syscalls.o:(.data.rel+0x3f8): undefined reference to `sc_create_module'
syscalls.o:(.data.rel+0x400): undefined reference to `sc_init_module'
syscalls.o:(.data.rel+0x408): undefined reference to `sc_delete_module'
syscalls.o:(.data.rel+0x410): undefined reference to `sc_get_kernel_syms'
syscalls.o:(.data.rel+0x418): undefined reference to `sc_quotactl'
syscalls.o:(.data.rel+0x420): undefined reference to `sc_getpgid'
syscalls.o:(.data.rel+0x428): undefined reference to `sc_fchdir'
syscalls.o:(.data.rel+0x430): undefined reference to `sc_bdflush'
syscalls.o:(.data.rel+0x438): undefined reference to `sc_sysfs'
syscalls.o:(.data.rel+0x440): undefined reference to `sc_personality'
syscalls.o:(.data.rel+0x448): undefined reference to `sc_afs_syscall'
syscalls.o:(.data.rel+0x450): undefined reference to `sc_setfsuid'
syscalls.o:(.data.rel+0x458): undefined reference to `sc_setfsgid'
syscalls.o:(.data.rel+0x460): undefined reference to `sc__llseek'
syscalls.o:(.data.rel+0x468): undefined reference to `sc_getdents'
syscalls.o:(.data.rel+0x470): undefined reference to `sc__newselect'
syscalls.o:(.data.rel+0x478): undefined reference to `sc_flock'
syscalls.o:(.data.rel+0x488): undefined reference to `sc_readv'
syscalls.o:(.data.rel+0x498): undefined reference to `sc_getsid'
syscalls.o:(.data.rel+0x4a0): undefined reference to `sc_fdatasync'
syscalls.o:(.data.rel+0x4a8): undefined reference to `sc__sysctl'
syscalls.o:(.data.rel+0x4d0): undefined reference to `sc_sched_setparam'
syscalls.o:(.data.rel+0x4d8): undefined reference to `sc_sched_getparam'
syscalls.o:(.data.rel+0x4e0): undefined reference to `sc_sched_setscheduler'
syscalls.o:(.data.rel+0x4e8): undefined reference to `sc_sched_getscheduler'
syscalls.o:(.data.rel+0x4f8): undefined reference to `sc_sched_get_priority_max'
syscalls.o:(.data.rel+0x500): undefined reference to `sc_sched_get_priority_min'
syscalls.o:(.data.rel+0x508): undefined reference to `sc_sched_rr_get_interval'
syscalls.o:(.data.rel+0x510): undefined reference to `sc_nanosleep'
syscalls.o:(.data.rel+0x520): undefined reference to `sc_setresuid'
syscalls.o:(.data.rel+0x528): undefined reference to `sc_getresuid'
syscalls.o:(.data.rel+0x530): undefined reference to `sc_query_module'
syscalls.o:(.data.rel+0x538): undefined reference to `sc_poll'
syscalls.o:(.data.rel+0x540): undefined reference to `sc_nfsservctl'
syscalls.o:(.data.rel+0x548): undefined reference to `sc_setresgid'
syscalls.o:(.data.rel+0x550): undefined reference to `sc_getresgid'
syscalls.o:(.data.rel+0x558): undefined reference to `sc_prctl'
syscalls.o:(.data.rel+0x560): undefined reference to `sc_rt_sigreturn'
syscalls.o:(.data.rel+0x568): undefined reference to `sc_rt_sigaction'
syscalls.o:(.data.rel+0x570): undefined reference to `sc_rt_sigprocmask'
syscalls.o:(.data.rel+0x578): undefined reference to `sc_rt_sigpending'
syscalls.o:(.data.rel+0x580): undefined reference to `sc_rt_sigtimedwait'
syscalls.o:(.data.rel+0x588): undefined reference to `sc_rt_sigqueueinfo'
syscalls.o:(.data.rel+0x590): undefined reference to `sc_rt_sigsuspend'
syscalls.o:(.data.rel+0x598): undefined reference to `sc_pread64'
syscalls.o:(.data.rel+0x5a0): undefined reference to `sc_pwrite64'
syscalls.o:(.data.rel+0x5a8): undefined reference to `sc_chown'
syscalls.o:(.data.rel+0x5b0): undefined reference to `sc_getcwd'
syscalls.o:(.data.rel+0x5b8): undefined reference to `sc_capget'
syscalls.o:(.data.rel+0x5c0): undefined reference to `sc_capset'
syscalls.o:(.data.rel+0x5c8): undefined reference to `sc_sigaltstack'
syscalls.o:(.data.rel+0x5d0): undefined reference to `sc_sendfile'
syscalls.o:(.data.rel+0x5d8): undefined reference to `sc_getpmsg'
syscalls.o:(.data.rel+0x5e0): undefined reference to `sc_putpmsg'
syscalls.o:(.data.rel+0x5e8): undefined reference to `sc_vfork'
syscalls.o:(.data.rel+0x5f0): undefined reference to `sc_ugetrlimit'
syscalls.o:(.data.rel+0x5f8): undefined reference to `sc_readahead'
syscalls.o:(.data.rel+0x608): undefined reference to `sc_truncate64'
syscalls.o:(.data.rel+0x618): undefined reference to `sc_stat64'
syscalls.o:(.data.rel+0x620): undefined reference to `sc_lstat64'
syscalls.o:(.data.rel+0x630): undefined reference to `sc_pciconfig_read'
syscalls.o:(.data.rel+0x638): undefined reference to `sc_pciconfig_write'
syscalls.o:(.data.rel+0x640): undefined reference to `sc_pciconfig_iobase'
syscalls.o:(.data.rel+0x648): undefined reference to `sc_multiplexer'
syscalls.o:(.data.rel+0x650): undefined reference to `sc_getdents64'
syscalls.o:(.data.rel+0x658): undefined reference to `sc_pivot_root'
syscalls.o:(.data.rel+0x660): undefined reference to `sc_fcntl64'
syscalls.o:(.data.rel+0x670): undefined reference to `sc_mincore'
syscalls.o:(.data.rel+0x678): undefined reference to `sc_gettid'
syscalls.o:(.data.rel+0x680): undefined reference to `sc_tkill'
syscalls.o:(.data.rel+0x688): undefined reference to `sc_setxattr'
syscalls.o:(.data.rel+0x690): undefined reference to `sc_lsetxattr'
syscalls.o:(.data.rel+0x698): undefined reference to `sc_fsetxattr'
syscalls.o:(.data.rel+0x6a0): undefined reference to `sc_getxattr'
syscalls.o:(.data.rel+0x6a8): undefined reference to `sc_lgetxattr'
syscalls.o:(.data.rel+0x6b0): undefined reference to `sc_fgetxattr'
syscalls.o:(.data.rel+0x6b8): undefined reference to `sc_listxattr'
syscalls.o:(.data.rel+0x6c0): undefined reference to `sc_llistxattr'
syscalls.o:(.data.rel+0x6c8): undefined reference to `sc_flistxattr'
syscalls.o:(.data.rel+0x6d0): undefined reference to `sc_removexattr'
syscalls.o:(.data.rel+0x6d8): undefined reference to `sc_lremovexattr'
syscalls.o:(.data.rel+0x6e0): undefined reference to `sc_fremovexattr'
syscalls.o:(.data.rel+0x6f0): undefined reference to `sc_sched_setaffinity'
syscalls.o:(.data.rel+0x6f8): undefined reference to `sc_sched_getaffinity'
syscalls.o:(.data.rel+0x700): undefined reference to `sc_NoSys'
syscalls.o:(.data.rel+0x708): undefined reference to `sc_tuxcall'
syscalls.o:(.data.rel+0x710): undefined reference to `sc_sendfile64'
syscalls.o:(.data.rel+0x718): undefined reference to `sc_io_setup'
syscalls.o:(.data.rel+0x720): undefined reference to `sc_io_destroy'
syscalls.o:(.data.rel+0x728): undefined reference to `sc_io_getevents'
syscalls.o:(.data.rel+0x730): undefined reference to `sc_io_submit'
syscalls.o:(.data.rel+0x738): undefined reference to `sc_io_cancel'
syscalls.o:(.data.rel+0x748): undefined reference to `sc_fadvise64'
syscalls.o:(.data.rel+0x758): undefined reference to `sc_lookup_dcookie'
syscalls.o:(.data.rel+0x760): undefined reference to `sc_epoll_create'
syscalls.o:(.data.rel+0x768): undefined reference to `sc_epoll_ctl'
syscalls.o:(.data.rel+0x770): undefined reference to `sc_epoll_wait'
syscalls.o:(.data.rel+0x778): undefined reference to `sc_remap_file_pages'
syscalls.o:(.data.rel+0x780): undefined reference to `sc_timer_create'
syscalls.o:(.data.rel+0x788): undefined reference to `sc_timer_settime'
syscalls.o:(.data.rel+0x790): undefined reference to `sc_timer_gettime'
syscalls.o:(.data.rel+0x798): undefined reference to `sc_timer_getoverrun'
syscalls.o:(.data.rel+0x7a0): undefined reference to `sc_timer_delete'
syscalls.o:(.data.rel+0x7a8): undefined reference to `sc_clock_settime'
syscalls.o:(.data.rel+0x7b0): undefined reference to `sc_clock_gettime'
syscalls.o:(.data.rel+0x7b8): undefined reference to `sc_clock_getres'
syscalls.o:(.data.rel+0x7c0): undefined reference to `sc_clock_nanosleep'
syscalls.o:(.data.rel+0x7c8): undefined reference to `sc_swapcontext'
syscalls.o:(.data.rel+0x7d0): undefined reference to `sc_tgkill'
syscalls.o:(.data.rel+0x7d8): undefined reference to `sc_utimes'
syscalls.o:(.data.rel+0x7e0): undefined reference to `sc_statfs64'
syscalls.o:(.data.rel+0x7e8): undefined reference to `sc_fstatfs64'
syscalls.o:(.data.rel+0x7f0): undefined reference to `sc_fadvise64_64'
syscalls.o:(.data.rel+0x7f8): undefined reference to `sc_rtas'
syscalls.o:(.data.rel+0x800): undefined reference to `sc_sys_debug_setcontext'
syscalls.o:(.data.rel+0x808): undefined reference to `sc_NoSys'
syscalls.o:(.data.rel+0x810): undefined reference to `sc_NoSys'
syscalls.o:(.data.rel+0x818): undefined reference to `sc_NoSys'
syscalls.o:(.data.rel+0x820): undefined reference to `sc_NoSys'
syscalls.o:(.data.rel+0x828): undefined reference to `sc_NoSys'
syscalls.o:(.data.rel+0x830): undefined reference to `sc_mq_open'
syscalls.o:(.data.rel+0x838): undefined reference to `sc_mq_unlink'
syscalls.o:(.data.rel+0x840): undefined reference to `sc_mq_timedsend'
syscalls.o:(.data.rel+0x848): undefined reference to `sc_mq_timedreceive'
syscalls.o:(.data.rel+0x850): undefined reference to `sc_mq_notify'
syscalls.o:(.data.rel+0x858): undefined reference to `sc_mq_getsetattr'
syscalls.o:(.data.rel+0x860): undefined reference to `sc_kexec_load'
syscalls.o:(.data.rel+0x868): undefined reference to `sc_add_key'
syscalls.o:(.data.rel+0x870): undefined reference to `sc_request_key'
syscalls.o:(.data.rel+0x878): undefined reference to `sc_keyctl'
syscalls.o:(.data.rel+0x880): undefined reference to `sc_waitid'
";



open(TMP, ">unimplemented.cc");
print TMP "#include \"Kernel.h\"\n\n";
@lines = split("\n", $linkererrors);
foreach $line (@lines)
{
    if(($line =~ /undefined/)&&($line =~ /sc_/))
    {
	($func) = $line =~ /\`(\S+)'/;
        $hash{$func} = 1;
    }
}

foreach $func (sort keys %hash)
{
    print TMP "uint64_t $func(SYSCALL_FCN_ARGS)\n";
    print TMP "{\n";
    print TMP "\treturn CNK_RC_FAILURE(ENOSYS);\n";
    print TMP "}\n\n\n";
}
close(TMP);
