/* begin_generated_IBM_copyright_prolog                             */
/*                                                                  */
/* This is an automatically generated copyright prolog.             */
/* After initializing,  DO NOT MODIFY OR MOVE                       */
/*  --------------------------------------------------------------- */
/*                                                                  */
/* Licensed Materials - Property of IBM                             */
/* Blue Gene/Q                                                      */
/* (C) Copyright IBM Corp.  2010, 2012                              */
/* US Government Users Restricted Rights - Use, duplication or      */
/*   disclosure restricted by GSA ADP Schedule Contract with IBM    */
/*   Corp.                                                          */
/*                                                                  */
/* This software is available to you under the Eclipse Public       */
/* License (EPL).                                                   */
/*                                                                  */
/*  --------------------------------------------------------------- */
/*                                                                  */
/* end_generated_IBM_copyright_prolog                               */

#ifndef _FW_MU_H
#define _FW_MU_H

// +-------------------------------------------------------------------------+
// | The following are control masks for the various Message Unit interrupt  |
// | status registers.  The general rule is that fatal, non-fatal and        |
// | correctable hardware errors are mapped to machine check.  Software      |
// | and software notification errors are mapped to non-critical interrupts. |
// +-------------------------------------------------------------------------+


#define MU_MASKED         0
#define MU_MACHINE_CHECK  1
#define MU_CRITICAL       2
#define MU_NON_CRITICAL   3


#define MU_ARLOG_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__ARLOG_INTERRUPTS_CONTROL_HIGH__ARLOG_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__ARLOG_INTERRUPTS_CONTROL_HIGH__ARLOG_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__ARLOG_INTERRUPTS_CONTROL_HIGH__ARLOG_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__ARLOG_INTERRUPTS_CONTROL_HIGH__ARLOG_ERR3_set(MU_MACHINE_CHECK) | \
  MU_DCR__ARLOG_INTERRUPTS_CONTROL_HIGH__ARLOG_ERR4_set(MU_MACHINE_CHECK) | \
  MU_DCR__ARLOG_INTERRUPTS_CONTROL_HIGH__ARLOG_ERR5_set(MU_MACHINE_CHECK) | \
  MU_DCR__ARLOG_INTERRUPTS_CONTROL_HIGH__ARLOG_ERR6_set(MU_MACHINE_CHECK) | \
  MU_DCR__ARLOG_INTERRUPTS_CONTROL_HIGH__ARLOG_ERR7_set(MU_MACHINE_CHECK) | \
  MU_DCR__ARLOG_INTERRUPTS_CONTROL_HIGH__ARLOG_ERR8_set(MU_MACHINE_CHECK) | \
  MU_DCR__ARLOG_INTERRUPTS_CONTROL_HIGH__ARLOG_ERR9_set(MU_MACHINE_CHECK) | \
  0)

#define MU_ECC_COUNT_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__ECC_COUNT_INTERRUPTS_CONTROL_HIGH__ECC_COUNT_OVER0_set(MU_MACHINE_CHECK) | \
  MU_DCR__ECC_COUNT_INTERRUPTS_CONTROL_HIGH__ECC_COUNT_OVER1_set(MU_MACHINE_CHECK) | \
  MU_DCR__ECC_COUNT_INTERRUPTS_CONTROL_HIGH__ECC_COUNT_OVER2_set(MU_MACHINE_CHECK) | \
  MU_DCR__ECC_COUNT_INTERRUPTS_CONTROL_HIGH__ECC_COUNT_OVER3_set(MU_MACHINE_CHECK) | \
  MU_DCR__ECC_COUNT_INTERRUPTS_CONTROL_HIGH__ECC_COUNT_OVER4_set(MU_MACHINE_CHECK) | \
  MU_DCR__ECC_COUNT_INTERRUPTS_CONTROL_HIGH__ECC_COUNT_OVER5_set(MU_MACHINE_CHECK) | \
  MU_DCR__ECC_COUNT_INTERRUPTS_CONTROL_HIGH__ECC_COUNT_OVER6_set(MU_MACHINE_CHECK) | \
  MU_DCR__ECC_COUNT_INTERRUPTS_CONTROL_HIGH__ECC_COUNT_OVER7_set(MU_MACHINE_CHECK) | \
  0)

#define MU_FIFO_INTERRUPTS_CONTROL_LOW (\
  MU_DCR__FIFO_INTERRUPTS_CONTROL_LOW__RMFIFO_INSUFFICIENT_SPACE_set(MU_NON_CRITICAL) | \
  0)

#define MU_ICSRAM_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR3_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR4_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR5_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR6_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR7_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR8_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR9_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR10_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR11_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR12_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR13_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR14_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR15_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR16_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR17_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR18_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR19_set(MU_MACHINE_CHECK) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR20_set(MU_NON_CRITICAL) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR21_set(MU_NON_CRITICAL) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR22_set(MU_NON_CRITICAL) | \
  MU_DCR__ICSRAM_INTERRUPTS_CONTROL_HIGH__ICSRAM_ERR23_set(MU_NON_CRITICAL) | \
  0)

#define MU_IME_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR3_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR4_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR5_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR6_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR7_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR8_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR9_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR10_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR11_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR12_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR13_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR14_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR15_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR16_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR17_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR18_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR19_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR20_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR21_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR22_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR23_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR24_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR25_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR26_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR27_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR28_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR29_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR30_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_HIGH__IME_ERR31_set(MU_MACHINE_CHECK) | \
  0)

#define MU_IME_INTERRUPTS_CONTROL_LOW (\
  MU_DCR__IME_INTERRUPTS_CONTROL_LOW__IME_ERR32_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_LOW__IME_ERR33_set(MU_MACHINE_CHECK) | \
  MU_DCR__IME_INTERRUPTS_CONTROL_LOW__IME_ERR34_set(MU_MACHINE_CHECK) | \
  0)

#define MU_IMU_ECC_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_UE0_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_UE1_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_UE2_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_UE3_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_UE4_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_UE5_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_UE6_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_UE7_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_UE8_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_UE9_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_UE10_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE0_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE1_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE2_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE3_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE4_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE5_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE6_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE7_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE8_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE9_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE10_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE11_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE12_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE13_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE14_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE15_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE16_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE17_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE18_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE19_set(MU_MACHINE_CHECK) | \
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_HIGH__IMU_ECC_CE20_set(MU_MACHINE_CHECK) | \
  0)

#define MU_IMU_ECC_INTERRUPTS_CONTROL_LOW (\
  MU_DCR__IMU_ECC_INTERRUPTS_CONTROL_LOW__IMU_ECC_CE21_set(MU_MACHINE_CHECK) | \
  0)

#define MU_MASTER_PORT0_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR3_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR4_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR5_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR6_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR7_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR8_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR9_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR10_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR11_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR12_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR13_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR14_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR15_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR16_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR17_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR18_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR19_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR20_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR21_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR22_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_FATAL_ERR23_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_SOFTWARE_ERR24_set(MU_NON_CRITICAL) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_SOFTWARE_ERR25_set(MU_NON_CRITICAL) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS_CONTROL_HIGH__XM0_CORR_ERR26_set(MU_MACHINE_CHECK) | \
  0)

#define MU_MASTER_PORT1_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR3_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR4_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR5_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR6_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR7_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR8_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR9_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR10_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR11_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR12_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR13_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR14_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR15_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR16_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR17_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR18_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR19_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR20_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR21_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR22_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_FATAL_ERR23_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_SOFTWARE_ERR24_set(MU_NON_CRITICAL) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_SOFTWARE_ERR25_set(MU_NON_CRITICAL) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS_CONTROL_HIGH__XM1_CORR_ERR26_set(MU_MACHINE_CHECK) | \
  0)

#define MU_MASTER_PORT2_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR3_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR4_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR5_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR6_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR7_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR8_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR9_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR10_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR11_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR12_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR13_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR14_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR15_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR16_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR17_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR18_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR19_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR20_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR21_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR22_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_FATAL_ERR23_set(MU_MACHINE_CHECK) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_SOFTWARE_ERR24_set(MU_NON_CRITICAL) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_SOFTWARE_ERR25_set(MU_NON_CRITICAL) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS_CONTROL_HIGH__XM2_CORR_ERR26_set(MU_MACHINE_CHECK) | \
  0)

#define MU_MCSRAM_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR3_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR4_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR5_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR6_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR7_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR8_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR9_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR10_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR11_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR12_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR13_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR14_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR15_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR16_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR17_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR18_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR19_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR20_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR21_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR22_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR23_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR24_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR25_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR26_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR27_set(MU_NON_CRITICAL) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR28_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR29_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_ERR30_set(MU_MACHINE_CHECK) | \
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_HIGH__MCSRAM_DD2_ERR0_set(MU_NON_CRITICAL) | \
  0)

#define MU_MCSRAM_INTERRUPTS_CONTROL_LOW (\
  MU_DCR__MCSRAM_INTERRUPTS_CONTROL_LOW__MCSRAM_DD2_ERR1_set(MU_NON_CRITICAL) | \
  0)

#define MU_MISC_ECC_CORR_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__MISC_ECC_CORR_INTERRUPTS_CONTROL_HIGH__MMREGS_ECC_CE0_set(MU_MACHINE_CHECK) | \
  MU_DCR__MISC_ECC_CORR_INTERRUPTS_CONTROL_HIGH__MMREGS_ECC_CE1_set(MU_MACHINE_CHECK) | \
  MU_DCR__MISC_ECC_CORR_INTERRUPTS_CONTROL_HIGH__MMREGS_ECC_CE2_set(MU_MACHINE_CHECK) | \
  MU_DCR__MISC_ECC_CORR_INTERRUPTS_CONTROL_HIGH__XS_ECC_CE0_set(MU_MACHINE_CHECK) | \
  MU_DCR__MISC_ECC_CORR_INTERRUPTS_CONTROL_HIGH__XS_ECC_CE1_set(MU_MACHINE_CHECK) | \
  MU_DCR__MISC_ECC_CORR_INTERRUPTS_CONTROL_HIGH__XS_ECC_CE2_set(MU_MACHINE_CHECK) | \
  0)

#define MU_MISC_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__MISC_INTERRUPTS_CONTROL_HIGH__ICSRAM_SELECT_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__MISC_INTERRUPTS_CONTROL_HIGH__ICSRAM_SELECT_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__MISC_INTERRUPTS_CONTROL_HIGH__ICSRAM_SELECT_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__MISC_INTERRUPTS_CONTROL_HIGH__ICSRAM_SELECT_ERR3_set(MU_NON_CRITICAL) | \
  MU_DCR__MISC_INTERRUPTS_CONTROL_HIGH__ICSRAM_SELECT_ERR4_set(MU_NON_CRITICAL) | \
  MU_DCR__MISC_INTERRUPTS_CONTROL_HIGH__ICSRAM_SELECT_ERR5_set(MU_NON_CRITICAL) | \
  MU_DCR__MISC_INTERRUPTS_CONTROL_HIGH__RAN_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__MISC_INTERRUPTS_CONTROL_HIGH__MU_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__MISC_INTERRUPTS_CONTROL_HIGH__MU_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__MISC_INTERRUPTS_CONTROL_HIGH__UPC_COUNTER_OVF_set(MU_MACHINE_CHECK) | \
  0)

#define MU_MMREGS_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_FATAL_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_FATAL_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_FATAL_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_FATAL_ERR3_set(MU_MACHINE_CHECK) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_FATAL_ERR4_set(MU_MACHINE_CHECK) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_FATAL_ERR5_set(MU_MACHINE_CHECK) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_FATAL_ERR6_set(MU_MACHINE_CHECK) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_FATAL_ERR7_set(MU_MACHINE_CHECK) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_FATAL_ERR8_set(MU_MACHINE_CHECK) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_SOFTWARE_ERR9_set(MU_NON_CRITICAL) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_SOFTWARE_ERR10_set(MU_NON_CRITICAL) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_SOFTWARE_ERR11_set(MU_NON_CRITICAL) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_SOFTWARE_ERR12_set(MU_NON_CRITICAL) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_SOFTWARE_ERR13_set(MU_NON_CRITICAL) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_SOFTWARE_ERR14_set(MU_NON_CRITICAL) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_SOFTWARE_ERR15_set(MU_NON_CRITICAL) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_SOFTWARE_ERR16_set(MU_NON_CRITICAL) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_SOFTWARE_ERR17_set(MU_NON_CRITICAL) | \
  MU_DCR__MMREGS_INTERRUPTS_CONTROL_HIGH__MMREGS_SOFTWARE_ERR18_set(MU_NON_CRITICAL) | \
  0)

#define MU_RCSRAM_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR3_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR4_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR5_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR6_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR7_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR8_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR9_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR10_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR11_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR12_set(MU_NON_CRITICAL) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR13_set(MU_NON_CRITICAL) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR14_set(MU_NON_CRITICAL) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR15_set(MU_NON_CRITICAL) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR16_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR17_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR18_set(MU_MACHINE_CHECK) | \
  MU_DCR__RCSRAM_INTERRUPTS_CONTROL_HIGH__RCSRAM_ERR19_set(MU_MACHINE_CHECK) | \
  0)

#define MU_RME_INTERRUPTS0_CONTROL_HIGH (\
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR3_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR4_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR5_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR6_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR7_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR8_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR9_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR10_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR11_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR12_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR13_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR14_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR15_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR16_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR17_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR18_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR19_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR20_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR21_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR22_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR23_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR24_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR25_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR26_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR27_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR28_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR29_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR30_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_HIGH__RME_ERR31_set(MU_MACHINE_CHECK) | \
  0)

#define MU_RME_INTERRUPTS0_CONTROL_LOW (\
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR32_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR33_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR34_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR35_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR36_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR37_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR38_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR39_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR40_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR41_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR42_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR43_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR44_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR45_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR46_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR47_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS0_CONTROL_LOW__RME_ERR48_set(MU_MACHINE_CHECK) | \
  0)

#define MU_RME_INTERRUPTS1_CONTROL_HIGH (\
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR49_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR50_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR51_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR52_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR53_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR54_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR55_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR56_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR57_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR58_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR59_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR60_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR61_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR62_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR63_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR64_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR65_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR66_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR67_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR68_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR69_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR70_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR71_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR72_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR73_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR74_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR75_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR76_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR77_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR78_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR79_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_HIGH__RME_ERR80_set(MU_MACHINE_CHECK) | \
  0)

#define MU_RME_INTERRUPTS1_CONTROL_LOW (\
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR81_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR82_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR83_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR84_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR85_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR86_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR87_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR88_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR89_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR90_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR91_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR92_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR93_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR94_set(MU_MACHINE_CHECK) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR95_set(MU_NON_CRITICAL) | \
  MU_DCR__RME_INTERRUPTS1_CONTROL_LOW__RME_ERR96_set(MU_MACHINE_CHECK) | \
  0)

#define MU_RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE0_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE1_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE2_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE3_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE4_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE5_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE6_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE7_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE8_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE9_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE10_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE11_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE12_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE13_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE14_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE15_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE16_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE17_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE18_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE19_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE20_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE21_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE22_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE23_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE24_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE25_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE26_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE27_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE28_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE29_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE30_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_HIGH__RMU_ECC_CE31_set(MU_MACHINE_CHECK) | \
  0)

#define MU_RMU_ECC_CORR_INTERRUPTS_CONTROL_LOW (\
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_LOW__RMU_ECC_CE32_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_LOW__RMU_ECC_CE33_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_LOW__RMU_ECC_CE34_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_LOW__RMU_ECC_CE35_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_LOW__RMU_ECC_CE36_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_LOW__RMU_ECC_CE37_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_LOW__RMU_ECC_CE38_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS_CONTROL_LOW__RMU_ECC_CE39_set(MU_MACHINE_CHECK) | \
  0)

#define MU_RMU_ECC_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE0_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE1_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE2_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE3_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE4_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE5_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE6_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE7_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE8_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE9_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE10_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE11_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE12_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE13_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE14_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE15_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE16_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE17_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE18_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE19_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE20_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE21_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE22_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE23_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE24_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE25_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE26_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE27_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE28_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE29_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE30_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_HIGH__RMU_ECC_UE31_set(MU_MACHINE_CHECK) | \
  0)

#define MU_RMU_ECC_INTERRUPTS_CONTROL_LOW (\
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_LOW__RMU_ECC_UE32_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_LOW__RMU_ECC_UE33_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_LOW__RMU_ECC_UE34_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_LOW__RMU_ECC_UE35_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_LOW__RMU_ECC_UE36_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_LOW__RMU_ECC_UE37_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_LOW__RMU_ECC_UE38_set(MU_MACHINE_CHECK) | \
  MU_DCR__RMU_ECC_INTERRUPTS_CONTROL_LOW__RMU_ECC_UE39_set(MU_MACHINE_CHECK) | \
  0)

#define MU_RPUTSRAM_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR3_set(MU_MACHINE_CHECK) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR4_set(MU_MACHINE_CHECK) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR5_set(MU_MACHINE_CHECK) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR6_set(MU_MACHINE_CHECK) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR7_set(MU_MACHINE_CHECK) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR8_set(MU_NON_CRITICAL) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR9_set(MU_NON_CRITICAL) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR10_set(MU_NON_CRITICAL) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR11_set(MU_NON_CRITICAL) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR12_set(MU_NON_CRITICAL) | \
  MU_DCR__RPUTSRAM_INTERRUPTS_CONTROL_HIGH__RPUTSRAM_ERR13_set(MU_NON_CRITICAL) | \
  0)

#define MU_SLAVE_PORT_INTERRUPTS_CONTROL_HIGH (\
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR0_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR1_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR2_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR3_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR4_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR5_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR6_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR7_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR8_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR9_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR10_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR11_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR12_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR13_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR14_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR15_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR16_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR17_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR18_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR19_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_FATAL_ERR20_set(MU_MACHINE_CHECK) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_SOFTWARE_ERR21_set(MU_NON_CRITICAL) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_SOFTWARE_ERR22_set(MU_NON_CRITICAL) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_SOFTWARE_ERR23_set(MU_NON_CRITICAL) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_SOFTWARE_ERR24_set(MU_NON_CRITICAL) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_SOFTWARE_ERR25_set(MU_NON_CRITICAL) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_SOFTWARE_ERR26_set(MU_NON_CRITICAL) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS_CONTROL_HIGH__XS_SOFTWARE_ERR27_set(MU_NON_CRITICAL) | \
  0)

// +-------------------------------------------------------------------------+
// | The following are interrupt status bit masks.  For each DCR containing  |
// | interrupt status bits, there is a separate mask for fatal, non-fatal,   |
// | and correctable errors.  Software and notification errors are not       |
// | considered here since they are the responsibility of the kernels.       |
// +-------------------------------------------------------------------------+

#define ARLOG_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__ARLOG_INTERRUPTS__ARLOG_ERR0_set(1) | \
  MU_DCR__ARLOG_INTERRUPTS__ARLOG_ERR1_set(1) | \
  MU_DCR__ARLOG_INTERRUPTS__ARLOG_ERR2_set(1) | \
  MU_DCR__ARLOG_INTERRUPTS__ARLOG_ERR7_set(1) | \
  MU_DCR__ARLOG_INTERRUPTS__ARLOG_ERR8_set(1) | \
  0 )

#define ARLOG_INTERRUPTS_NON_FATAL_MASK ( \
  MU_DCR__ARLOG_INTERRUPTS__ARLOG_ERR3_set(1) | \
  MU_DCR__ARLOG_INTERRUPTS__ARLOG_ERR4_set(1) | \
  MU_DCR__ARLOG_INTERRUPTS__ARLOG_ERR5_set(1) | \
  MU_DCR__ARLOG_INTERRUPTS__ARLOG_ERR6_set(1) | \
  MU_DCR__ARLOG_INTERRUPTS__ARLOG_ERR9_set(1) | \
  0 )

#define ARLOG_INTERRUPTS_CORRECTABLE_MASK ( \
  0 )

#define ECC_COUNT_INTERRUPTS_FATAL_MASK ( \
  0 )

#define ECC_COUNT_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define ECC_COUNT_INTERRUPTS_CORRECTABLE_MASK ( \
  MU_DCR__ECC_COUNT_INTERRUPTS__ECC_COUNT_OVER0_set(1) | \
  MU_DCR__ECC_COUNT_INTERRUPTS__ECC_COUNT_OVER1_set(1) | \
  MU_DCR__ECC_COUNT_INTERRUPTS__ECC_COUNT_OVER2_set(1) | \
  MU_DCR__ECC_COUNT_INTERRUPTS__ECC_COUNT_OVER3_set(1) | \
  MU_DCR__ECC_COUNT_INTERRUPTS__ECC_COUNT_OVER4_set(1) | \
  MU_DCR__ECC_COUNT_INTERRUPTS__ECC_COUNT_OVER5_set(1) | \
  MU_DCR__ECC_COUNT_INTERRUPTS__ECC_COUNT_OVER6_set(1) | \
  MU_DCR__ECC_COUNT_INTERRUPTS__ECC_COUNT_OVER7_set(1) | \
  0 )

#define FIFO_INTERRUPTS_FATAL_MASK ( \
  0 )

#define FIFO_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define FIFO_INTERRUPTS_CORRECTABLE_MASK ( \
  0 )

#define ICSRAM_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR0_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR1_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR2_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR3_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR4_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR5_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR6_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR7_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR8_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR9_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR10_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR11_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR12_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR13_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR14_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR15_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR16_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR17_set(1) | \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR18_set(1) | \
  0 )

#define ICSRAM_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define ICSRAM_INTERRUPTS_CORRECTABLE_MASK ( \
  MU_DCR__ICSRAM_INTERRUPTS__ICSRAM_ERR19_set(1) | \
  0 )

#define IME_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__IME_INTERRUPTS__IME_ERR0_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR1_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR2_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR3_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR4_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR5_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR6_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR7_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR8_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR9_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR10_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR11_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR12_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR13_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR14_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR15_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR16_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR17_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR18_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR19_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR20_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR21_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR22_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR23_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR24_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR25_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR26_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR27_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR28_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR29_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR30_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR31_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR32_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR33_set(1) | \
  MU_DCR__IME_INTERRUPTS__IME_ERR34_set(1) | \
  0 )

#define IME_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define IME_INTERRUPTS_CORRECTABLE_MASK ( \
  0 )

#define IMU_ECC_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_UE0_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_UE1_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_UE2_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_UE3_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_UE4_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_UE5_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_UE6_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_UE7_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_UE8_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_UE9_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_UE10_set(1) | \
  0 )

#define IMU_ECC_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define IMU_ECC_INTERRUPTS_CORRECTABLE_MASK ( \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE0_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE1_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE2_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE3_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE4_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE5_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE6_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE7_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE8_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE9_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE10_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE11_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE12_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE13_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE14_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE15_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE16_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE17_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE18_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE19_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE20_set(1) | \
  MU_DCR__IMU_ECC_INTERRUPTS__IMU_ECC_CE21_set(1) | \
  0 )

#define MASTER_PORT0_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR0_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR1_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR2_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR3_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR4_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR5_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR6_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR7_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR8_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR9_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR10_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR11_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR12_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR13_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR14_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR15_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR16_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR17_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR18_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR19_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR20_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR21_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR22_set(1) | \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_FATAL_ERR23_set(1) | \
  0 )

#define MASTER_PORT0_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define MASTER_PORT0_INTERRUPTS_CORRECTABLE_MASK ( \
  MU_DCR__MASTER_PORT0_INTERRUPTS__XM0_CORR_ERR26_set(1) | \
  0 )

#define MASTER_PORT1_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR0_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR1_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR2_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR3_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR4_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR5_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR6_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR7_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR8_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR9_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR10_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR11_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR12_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR13_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR14_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR15_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR16_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR17_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR18_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR19_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR20_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR21_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR22_set(1) | \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_FATAL_ERR23_set(1) | \
  0 )

#define MASTER_PORT1_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define MASTER_PORT1_INTERRUPTS_CORRECTABLE_MASK ( \
  MU_DCR__MASTER_PORT1_INTERRUPTS__XM1_CORR_ERR26_set(1) | \
  0 )

#define MASTER_PORT2_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR0_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR1_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR2_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR3_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR4_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR5_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR6_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR7_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR8_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR9_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR10_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR11_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR12_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR13_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR14_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR15_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR16_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR17_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR18_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR19_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR20_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR21_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR22_set(1) | \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_FATAL_ERR23_set(1) | \
  0 )

#define MASTER_PORT2_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define MASTER_PORT2_INTERRUPTS_CORRECTABLE_MASK ( \
  MU_DCR__MASTER_PORT2_INTERRUPTS__XM2_CORR_ERR26_set(1) | \
  0 )

#define MCSRAM_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR0_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR1_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR2_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR3_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR4_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR5_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR6_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR7_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR8_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR9_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR10_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR11_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR12_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR13_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR14_set(1) | \
  0 )

#define MCSRAM_INTERRUPTS_NON_FATAL_MASK ( \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR28_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR29_set(1) | \
  MU_DCR__MCSRAM_INTERRUPTS__MCSRAM_ERR30_set(1) | \
  0 )

#define MCSRAM_INTERRUPTS_CORRECTABLE_MASK ( \
  0 )

#define MISC_ECC_CORR_INTERRUPTS_FATAL_MASK ( \
  0 )

#define MISC_ECC_CORR_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define MISC_ECC_CORR_INTERRUPTS_CORRECTABLE_MASK ( \
  MU_DCR__MISC_ECC_CORR_INTERRUPTS__MMREGS_ECC_CE0_set(1) | \
  MU_DCR__MISC_ECC_CORR_INTERRUPTS__MMREGS_ECC_CE1_set(1) | \
  MU_DCR__MISC_ECC_CORR_INTERRUPTS__MMREGS_ECC_CE2_set(1) | \
  MU_DCR__MISC_ECC_CORR_INTERRUPTS__XS_ECC_CE0_set(1) | \
  MU_DCR__MISC_ECC_CORR_INTERRUPTS__XS_ECC_CE1_set(1) | \
  MU_DCR__MISC_ECC_CORR_INTERRUPTS__XS_ECC_CE2_set(1) | \
  0 )

#define MISC_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__MISC_INTERRUPTS__ICSRAM_SELECT_ERR0_set(1) | \
  MU_DCR__MISC_INTERRUPTS__ICSRAM_SELECT_ERR1_set(1) | \
  MU_DCR__MISC_INTERRUPTS__MU_ERR0_set(1) | \
  MU_DCR__MISC_INTERRUPTS__MU_ERR1_set(1) | \
  0 )

#define MISC_INTERRUPTS_NON_FATAL_MASK ( \
  MU_DCR__MISC_INTERRUPTS__ICSRAM_SELECT_ERR2_set(1) | \
  MU_DCR__MISC_INTERRUPTS__RAN_ERR0_set(1) | \
  MU_DCR__MISC_INTERRUPTS__UPC_COUNTER_OVF_set(1) | \
  0 )

#define MISC_INTERRUPTS_CORRECTABLE_MASK ( \
  0 )

#define MMREGS_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__MMREGS_INTERRUPTS__MMREGS_FATAL_ERR0_set(1) | \
  MU_DCR__MMREGS_INTERRUPTS__MMREGS_FATAL_ERR1_set(1) | \
  MU_DCR__MMREGS_INTERRUPTS__MMREGS_FATAL_ERR2_set(1) | \
  MU_DCR__MMREGS_INTERRUPTS__MMREGS_FATAL_ERR3_set(1) | \
  MU_DCR__MMREGS_INTERRUPTS__MMREGS_FATAL_ERR4_set(1) | \
  MU_DCR__MMREGS_INTERRUPTS__MMREGS_FATAL_ERR5_set(1) | \
  MU_DCR__MMREGS_INTERRUPTS__MMREGS_FATAL_ERR6_set(1) | \
  MU_DCR__MMREGS_INTERRUPTS__MMREGS_FATAL_ERR7_set(1) | \
  MU_DCR__MMREGS_INTERRUPTS__MMREGS_FATAL_ERR8_set(1) | \
  0 )

#define MMREGS_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define MMREGS_INTERRUPTS_CORRECTABLE_MASK ( \
  0 )

#define RCSRAM_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR0_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR1_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR2_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR3_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR4_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR5_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR6_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR7_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR8_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR9_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR10_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR11_set(1) | \
  0 )

#define RCSRAM_INTERRUPTS_NON_FATAL_MASK ( \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR16_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR17_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR18_set(1) | \
  MU_DCR__RCSRAM_INTERRUPTS__RCSRAM_ERR19_set(1) | \
  0 )

#define RCSRAM_INTERRUPTS_CORRECTABLE_MASK ( \
  0 )

#define RME_INTERRUPTS0_FATAL_MASK ( \
  MU_DCR__RME_INTERRUPTS0__RME_ERR0_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR1_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR2_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR3_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR4_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR7_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR8_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR9_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR10_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR13_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR14_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR15_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR16_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR19_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR20_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR21_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR22_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR25_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR26_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR27_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR28_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR31_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR32_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR33_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR34_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR37_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR38_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR39_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR40_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR43_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR44_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR45_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR46_set(1) | \
  0 )

#define RME_INTERRUPTS0_NON_FATAL_MASK ( \
  MU_DCR__RME_INTERRUPTS0__RME_ERR6_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR12_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR18_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR24_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR30_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR36_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR42_set(1) | \
  MU_DCR__RME_INTERRUPTS0__RME_ERR48_set(1) | \
  0 )

#define RME_INTERRUPTS0_CORRECTABLE_MASK ( \
  0 )

#define RME_INTERRUPTS1_FATAL_MASK ( \
  MU_DCR__RME_INTERRUPTS1__RME_ERR49_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR50_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR51_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR52_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR55_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR56_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR57_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR58_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR61_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR62_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR63_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR64_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR67_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR68_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR69_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR70_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR73_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR74_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR75_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR76_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR79_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR80_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR81_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR82_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR85_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR86_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR87_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR88_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR91_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR92_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR93_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR94_set(1) | \
  0 )

#define RME_INTERRUPTS1_NON_FATAL_MASK ( \
  MU_DCR__RME_INTERRUPTS1__RME_ERR54_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR60_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR66_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR72_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR78_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR84_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR90_set(1) | \
  MU_DCR__RME_INTERRUPTS1__RME_ERR96_set(1) | \
  0 )

#define RME_INTERRUPTS1_CORRECTABLE_MASK ( \
  0 )

#define RMU_ECC_CORR_INTERRUPTS_FATAL_MASK ( \
  0 )

#define RMU_ECC_CORR_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define RMU_ECC_CORR_INTERRUPTS_CORRECTABLE_MASK ( \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE0_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE1_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE2_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE3_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE4_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE5_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE6_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE7_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE8_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE9_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE10_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE11_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE12_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE13_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE14_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE15_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE16_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE17_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE18_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE19_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE20_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE21_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE22_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE23_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE24_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE25_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE26_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE27_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE28_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE29_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE30_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE31_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE32_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE33_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE34_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE35_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE36_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE37_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE38_set(1) | \
  MU_DCR__RMU_ECC_CORR_INTERRUPTS__RMU_ECC_CE39_set(1) | \
  0 )

#define RMU_ECC_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE0_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE1_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE2_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE3_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE4_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE5_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE6_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE7_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE8_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE9_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE10_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE11_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE12_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE13_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE14_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE15_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE16_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE17_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE18_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE19_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE20_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE21_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE22_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE23_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE24_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE25_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE26_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE27_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE28_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE29_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE30_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE31_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE32_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE33_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE34_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE35_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE36_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE37_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE38_set(1) | \
  MU_DCR__RMU_ECC_INTERRUPTS__RMU_ECC_UE39_set(1) | \
  0 )

#define RMU_ECC_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define RMU_ECC_INTERRUPTS_CORRECTABLE_MASK ( \
  0 )

#define RPUTSRAM_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__RPUTSRAM_INTERRUPTS__RPUTSRAM_ERR0_set(1) | \
  MU_DCR__RPUTSRAM_INTERRUPTS__RPUTSRAM_ERR1_set(1) | \
  MU_DCR__RPUTSRAM_INTERRUPTS__RPUTSRAM_ERR2_set(1) | \
  MU_DCR__RPUTSRAM_INTERRUPTS__RPUTSRAM_ERR4_set(1) | \
  MU_DCR__RPUTSRAM_INTERRUPTS__RPUTSRAM_ERR5_set(1) | \
  0 )

#define RPUTSRAM_INTERRUPTS_NON_FATAL_MASK ( \
  MU_DCR__RPUTSRAM_INTERRUPTS__RPUTSRAM_ERR3_set(1) | \
  MU_DCR__RPUTSRAM_INTERRUPTS__RPUTSRAM_ERR6_set(1) | \
  MU_DCR__RPUTSRAM_INTERRUPTS__RPUTSRAM_ERR7_set(1) | \
  0 )

#define RPUTSRAM_INTERRUPTS_CORRECTABLE_MASK ( \
  0 )

#define SLAVE_PORT_INTERRUPTS_FATAL_MASK ( \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR0_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR1_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR2_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR3_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR4_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR5_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR6_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR7_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR8_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR9_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR10_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR11_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR12_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR13_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR14_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR15_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR16_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR17_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR18_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR19_set(1) | \
  MU_DCR__SLAVE_PORT_INTERRUPTS__XS_FATAL_ERR20_set(1) | \
  0 )

#define SLAVE_PORT_INTERRUPTS_NON_FATAL_MASK ( \
  0 )

#define SLAVE_PORT_INTERRUPTS_CORRECTABLE_MASK ( \
  0 )



typedef struct MuMachineCheckData_t {
  uint32_t dcrAddress;       // DCR containing interrupt bits
  struct {
    uint64_t mask;           // Mask of interrupt bits
    uint64_t additionalInfo; // DCR address of additional info (intinfo) register
  } level[2];                // lvl 0 = non-fatal, lvl 1 = fatal
} MU_MachineCheckData_t;

int fw_mu_captureRMEInterrupts0(uint64_t*, unsigned*, MU_MachineCheckData_t*, unsigned);
int fw_mu_captureRMEInterrupts1(uint64_t*, unsigned*, MU_MachineCheckData_t*, unsigned);
int fw_mu_captureIMEInterrupts(uint64_t*, unsigned*, MU_MachineCheckData_t*, unsigned);
int fw_mu_eccCountInterrupts(uint64_t*, unsigned*, MU_MachineCheckData_t*, unsigned);
int fw_mu_handleIMUCorrectables(uint64_t*, unsigned*, MU_MachineCheckData_t*, unsigned);

MU_MachineCheckData_t MU_MachineCheck_Data[] = {

  { MU_DCR(ECC_COUNT_INTERRUPTS__MACHINE_CHECK), 
    {
      { ECC_COUNT_INTERRUPTS_NON_FATAL_MASK | ECC_COUNT_INTERRUPTS_CORRECTABLE_MASK, (uint64_t)fw_mu_eccCountInterrupts },
      { ECC_COUNT_INTERRUPTS_FATAL_MASK, 0 },
    },
  },


  { MU_DCR(ARLOG_INTERRUPTS__MACHINE_CHECK), 
    {
      { ARLOG_INTERRUPTS_NON_FATAL_MASK | ARLOG_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { ARLOG_INTERRUPTS_FATAL_MASK, 0 },
    },
  },

  // NOTE: FIFO_INTERRUPTS has no machine check bits

  { MU_DCR(ICSRAM_INTERRUPTS__MACHINE_CHECK), 
    {
      { ICSRAM_INTERRUPTS_NON_FATAL_MASK | ICSRAM_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { ICSRAM_INTERRUPTS_FATAL_MASK, 0 },
    },
  },
  { MU_DCR(MCSRAM_INTERRUPTS__MACHINE_CHECK), 
    {
      { MCSRAM_INTERRUPTS_NON_FATAL_MASK | MCSRAM_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { MCSRAM_INTERRUPTS_FATAL_MASK, MU_DCR(MCSRAM_ERR_FIFO_ID) },
    },
  },
  { MU_DCR(RCSRAM_INTERRUPTS__MACHINE_CHECK), 
    {
      { RCSRAM_INTERRUPTS_NON_FATAL_MASK | RCSRAM_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { RCSRAM_INTERRUPTS_FATAL_MASK, 0 },
    },
  },
  { MU_DCR(RPUTSRAM_INTERRUPTS__MACHINE_CHECK), 
    {
      { RPUTSRAM_INTERRUPTS_NON_FATAL_MASK | RPUTSRAM_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { RPUTSRAM_INTERRUPTS_FATAL_MASK, 0 },
    },
  },
  { MU_DCR(MISC_ECC_CORR_INTERRUPTS__MACHINE_CHECK), 
    {
      { MISC_ECC_CORR_INTERRUPTS_NON_FATAL_MASK | MISC_ECC_CORR_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { MISC_ECC_CORR_INTERRUPTS_FATAL_MASK, 0 },
    },
  },
  { MU_DCR(RME_INTERRUPTS0__MACHINE_CHECK), 
    {
      { RME_INTERRUPTS0_NON_FATAL_MASK | RME_INTERRUPTS0_CORRECTABLE_MASK, 0 },
      { RME_INTERRUPTS0_FATAL_MASK, (uint64_t)fw_mu_captureRMEInterrupts0 },
    },
  },
  { MU_DCR(RME_INTERRUPTS1__MACHINE_CHECK), 
    {
      { RME_INTERRUPTS1_NON_FATAL_MASK | RME_INTERRUPTS1_CORRECTABLE_MASK, 0 },
      { RME_INTERRUPTS1_FATAL_MASK, (uint64_t)fw_mu_captureRMEInterrupts1 },
    },
  },


  { MU_DCR(IME_INTERRUPTS__MACHINE_CHECK), 
    {
      { IME_INTERRUPTS_NON_FATAL_MASK | IME_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { IME_INTERRUPTS_FATAL_MASK, (uint64_t) fw_mu_captureIMEInterrupts },
    },
  },
  { MU_DCR(IMU_ECC_INTERRUPTS__MACHINE_CHECK), 
    {
      { IMU_ECC_INTERRUPTS_NON_FATAL_MASK | IMU_ECC_INTERRUPTS_CORRECTABLE_MASK, (uint64_t)fw_mu_handleIMUCorrectables },
      { IMU_ECC_INTERRUPTS_FATAL_MASK, 0 },
    },
  },
  { MU_DCR(MASTER_PORT0_INTERRUPTS__MACHINE_CHECK), 
    {
      { MASTER_PORT0_INTERRUPTS_NON_FATAL_MASK | MASTER_PORT0_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { MASTER_PORT0_INTERRUPTS_FATAL_MASK, 0 },
    },
  },
  { MU_DCR(MASTER_PORT1_INTERRUPTS__MACHINE_CHECK), 
    {
      { MASTER_PORT1_INTERRUPTS_NON_FATAL_MASK | MASTER_PORT1_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { MASTER_PORT1_INTERRUPTS_FATAL_MASK, 0 },
    },
  },
  { MU_DCR(MASTER_PORT2_INTERRUPTS__MACHINE_CHECK), 
    {
      { MASTER_PORT2_INTERRUPTS_NON_FATAL_MASK | MASTER_PORT2_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { MASTER_PORT2_INTERRUPTS_FATAL_MASK, 0 },
    },
  },
  { MU_DCR(MISC_INTERRUPTS__MACHINE_CHECK), 
    {
      { MISC_INTERRUPTS_NON_FATAL_MASK | MISC_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { MISC_INTERRUPTS_FATAL_MASK, 0 },
    },
  },
  { MU_DCR(MMREGS_INTERRUPTS__MACHINE_CHECK), 
    {
      { MMREGS_INTERRUPTS_NON_FATAL_MASK | MMREGS_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { MMREGS_INTERRUPTS_FATAL_MASK, 0 },
    },
  },
  { MU_DCR(RMU_ECC_CORR_INTERRUPTS__MACHINE_CHECK), 
    {
      { RMU_ECC_CORR_INTERRUPTS_NON_FATAL_MASK | RMU_ECC_CORR_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { RMU_ECC_CORR_INTERRUPTS_FATAL_MASK, 0 },
    },
  },
  { MU_DCR(RMU_ECC_INTERRUPTS__MACHINE_CHECK), 
    {
      { RMU_ECC_INTERRUPTS_NON_FATAL_MASK | RMU_ECC_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { RMU_ECC_INTERRUPTS_FATAL_MASK, 0 },
    },
  },
  { MU_DCR(SLAVE_PORT_INTERRUPTS__MACHINE_CHECK), 
    {
      { SLAVE_PORT_INTERRUPTS_NON_FATAL_MASK | SLAVE_PORT_INTERRUPTS_CORRECTABLE_MASK, 0 },
      { SLAVE_PORT_INTERRUPTS_FATAL_MASK, MU_DCR(XS_ERR_INFO) },
    },
  },
};


#endif
