/* begin_generated_IBM_copyright_prolog                             */
/*                                                                  */
/* This is an automatically generated copyright prolog.             */
/* After initializing,  DO NOT MODIFY OR MOVE                       */
/*  --------------------------------------------------------------- */
/*                                                                  */
/* Licensed Materials - Property of IBM                             */
/* Blue Gene/Q                                                      */
/* (C) Copyright IBM Corp.  2010, 2012                              */
/* US Government Users Restricted Rights - Use, duplication or      */
/*   disclosure restricted by GSA ADP Schedule Contract with IBM    */
/*   Corp.                                                          */
/*                                                                  */
/* This software is available to you under the Eclipse Public       */
/* License (EPL).                                                   */
/*                                                                  */
/*  --------------------------------------------------------------- */
/*                                                                  */
/* end_generated_IBM_copyright_prolog                               */

#ifndef _FW_REGS_H_ // Prevent multiple inclusion.
#define _FW_REGS_H_


#define NUM_GPRS  (32) //
//#define NUM_FPRS  (32) //
#define NUM_SPRG  (10) // SPRG[0..8], and VRSAVE.
#define NUM_GSPRG ( 4) // If no active Hypervisor, there are also 4 Guest SPRGs: GPSRG[0..3]

// Regs_t structure element offsets, generated by tools/regs_ofs.c.
#define REGS_SIZEOF       (0x0130)
//
#define REGS_OFS_GPR0     (0x0000)
#define REGS_OFS_GPR1     (0x0008)
#define REGS_OFS_GPR2     (0x0010)
#define REGS_OFS_GPR3     (0x0018)
#define REGS_OFS_GPR4     (0x0020)
#define REGS_OFS_GPR5     (0x0028)
#define REGS_OFS_GPR6     (0x0030)
#define REGS_OFS_GPR7     (0x0038)
#define REGS_OFS_GPR8     (0x0040)
#define REGS_OFS_GPR9     (0x0048)
#define REGS_OFS_GPR10    (0x0050)
#define REGS_OFS_GPR11    (0x0058)
#define REGS_OFS_GPR12    (0x0060)
#define REGS_OFS_GPR13    (0x0068)
#define REGS_OFS_GPR14    (0x0070)
#define REGS_OFS_GPR15    (0x0078)
#define REGS_OFS_GPR16    (0x0080)
#define REGS_OFS_GPR17    (0x0088)
#define REGS_OFS_GPR18    (0x0090)
#define REGS_OFS_GPR19    (0x0098)
#define REGS_OFS_GPR20    (0x00a0)
#define REGS_OFS_GPR21    (0x00a8)
#define REGS_OFS_GPR22    (0x00b0)
#define REGS_OFS_GPR23    (0x00b8)
#define REGS_OFS_GPR24    (0x00c0)
#define REGS_OFS_GPR25    (0x00c8)
#define REGS_OFS_GPR26    (0x00d0)
#define REGS_OFS_GPR27    (0x00d8)
#define REGS_OFS_GPR28    (0x00e0)
#define REGS_OFS_GPR29    (0x00e8)
#define REGS_OFS_GPR30    (0x00f0)
#define REGS_OFS_GPR31    (0x00f8)
//
#define REGS_OFS_IP       (0x0100)
#define REGS_OFS_MSR      (0x0108)
#define REGS_OFS_CR       (0x0110)
#define REGS_OFS_LR       (0x0118)
#define REGS_OFS_XER      (0x0120)
#define REGS_OFS_CTR      (0x0128)
//

#define _ABI_STACK_TAIL             (256)       // really ~224. Compiler dependent.
#define STACK_FRAME_SIZE           (128)
#define INT_FRAME_SIZE             (STACK_FRAME_SIZE + REGS_SIZEOF + _ABI_STACK_TAIL)

#if !defined(__ASSEMBLY__)

#include <stdint.h>

#include <hwi/include/common/bgq_alignment.h>
#include <hwi/include/bqc/A2_core.h>


//
// This structure contains no per-core SPRs, only per-thread SPRs.
//
// NOTE: If changing this structure, update tools/regs_ofs.c and
//       rerun it to generate the structure offsets above.
//
typedef struct Fw_Regs_t {
  uint64_t gpr[ NUM_GPRS ];
  uint64_t ip;            // from (mc|c)srr0
  uint64_t msr;
  uint64_t cr;
  uint64_t lr;
  uint64_t xer;
  uint64_t ctr;
} ALIGN_L1D_CACHE FW_Regs_t;

#endif // __ASSEMBLY__

#endif // Add nothing below this line.
