/* begin_generated_IBM_copyright_prolog                             */
/*                                                                  */
/* This is an automatically generated copyright prolog.             */
/* After initializing,  DO NOT MODIFY OR MOVE                       */
/* ================================================================ */
/*                                                                  */
/* Licensed Materials - Property of IBM                             */
/*                                                                  */
/* Blue Gene/Q                                                      */
/*                                                                  */
/* (C) Copyright IBM Corp.  2011, 2012                              */
/*                                                                  */
/* US Government Users Restricted Rights -                          */
/* Use, duplication or disclosure restricted                        */
/* by GSA ADP Schedule Contract with IBM Corp.                      */
/*                                                                  */
/* This software is available to you under the                      */
/* Eclipse Public License (EPL).                                    */
/*                                                                  */
/* ================================================================ */
/*                                                                  */
/* end_generated_IBM_copyright_prolog                               */
//******************************************************************************
// RAS event meta-data for all RAS events generated by the env monitor
//******************************************************************************
// All must be in the range of 0x00061000  to 0x00061fff
//******************************************************************************


/*
<rasevent  id="0x00061001"  component="MMCS"
  category="Node_Board"
  severity="WARN"
  message="MMCS could not contact node board at location $(BG_LOC)."
  description="MMCS attempted to read environmentals from the node board at the specified location, and received an error.  No environmentals will be reported for this polling interval, for the board."
  service_action="If the board continues to have this error, run diagnostics on the node board."
  relevant_diags="nodeboard"
 />

<rasevent  id="0x00061002"  component="MMCS"
  category="Service_Card"
  severity="WARN"
  message="MMCS could not contact service card at location $(BG_LOC)."
  description="MMCS attempted to read environmentals from the service card at the specified location, and received an error.  No environmentals will be reported for this polling interval, for the card."
  service_action="If the card continues to have this error, run diagnostics on the service card."
  relevant_diags="servicecard"
 />

<rasevent  id="0x00061003"  component="MMCS"
  category="AC_TO_DC_PWR"
  severity="WARN"
  message="MMCS could not contact bulk power module at location $(BG_LOC)."
  description="MMCS attempted to read environmentals from the bulk power module at the specified location, and received an error.  No environmentals will be reported for this polling interval, for the module."
  service_action="If the bulk power module continues to have this error, look at the LEDs on the modules to determine if there is a failure."
  relevant_diags=""
 />

<rasevent  id="0x00061004"  component="MMCS"
  category="IO_Board"
  severity="WARN"
  message="MMCS could not contact IO board at location $(BG_LOC)."
  description="MMCS attempted to read environmentals from the IO board at the specified location, and received an error.  No environmentals will be reported for this polling interval, for the board."
  service_action="If the board continues to have this error, run diagnostics on the failing board."
  relevant_diags="ioboard"
 />

 <rasevent  id="0x00061005"  component="MMCS"
  category="Coolant_Monitor"
  severity="WARN"
  message="MMCS could not contact coolant monitor at location $(BG_LOC)."
  description="MMCS attempted to read environmentals from the coolant monitor at the specified location, and received an error.  No environmentals will be reported for this polling interval."
  service_action="If the coolant monitor continues to have this error, check the power modules on the midplane to make sure they are supplying power to the coolant monitor."
  relevant_diags=""
 />

 <rasevent  id="0x00061006"  component="MMCS"
  category="Coolant_Monitor"
  severity="WARN"
  message="Health Check detected an error on the coolant monitor connected to the service card at location $(BG_LOC). The condition is related to $(COND)."
  description="The Health Check analyzed the coolant monitor at the specified location, and received an indication that one or more faults occurred. This is an indication that one or more of the coolant monitor alarm thresholds has been reached.  The faults indicated above did not result in water and or power being shut-off on the rack."
  service_action="If the coolant monitor continues to post this error, and can not be explained by some specific environmental characteristic of the facility or specific action done to the rack,  then a more in depth inspection of the rack and and its connections is warranted."
  relevant_diags=""
  details="COND"
 />

 <rasevent  id="0x00061007"  component="MMCS"
  category="Service_Card"
  severity="WARN"
  message="Health Check detected an incorrect clock frequency $(FREQ) on the service card at location $(BG_LOC)."
  description="The Health Check analyzed the service card at the specified location, and found a clock frequency that was outside the expected range."
  service_action="If the card continues to have this error, run diagnostics on the service card. The problem may also be originating from the master clock card."
  relevant_diags="servicecard"
  details="FREQ"
  />

  <rasevent  id="0x00061008"  component="MMCS"
  category="Service_Card"
  severity="WARN"
  message="Health Check detected an overtemp condition on the service card at location $(BG_LOC).  The temperature $(ACTUAL) is above the expected maximum temperature of $(EXP). "
  description="The Health Check analyzed the service card at the specified location, and found a temperature that was outside the expected range."
  service_action="If the card continues to have this error, run diagnostics on the service card.  Check for temperature-related RAS events on other hardware to determine if the problem is widespread or isolated to this card."
  relevant_diags="servicecard"
  details="ACTUAL, EXP"
  />

  <rasevent  id="0x00061009"  component="MMCS"
  category="IO_Board"
  severity="WARN"
  message="Health Check detected an incorrect clock frequency $(FREQ) on the IO board at location $(BG_LOC)."
  description="The Health Check analyzed the IO board at the specified location, and found a clock frequency that was outside the expected range."
  service_action="If the card continues to have this error, run diagnostics on the IO board. The problem may also be originating from the master clock card."
  relevant_diags="ioboard"
  details="FREQ"
  />

  <rasevent  id="0x0006100A"  component="MMCS"
  category="IO_Board"
  severity="WARN"
  message="Health Check detected an abnormal status flag set for the IO board at location $(BG_LOC).  The status flag is for $(COMP)."
  description="The Health Check analyzed the IO board at the specified location, and found a status flag set for an abnormal condition."
  service_action="If the card continues to have this error, run diagnostics on the IO board."
  relevant_diags="ioboard"
  details="COMP"
  />

  <rasevent  id="0x0006100B"  component="MMCS"
  category="DCA"
  severity="WARN"
  message="Health Check detected an abnormal condition for the Direct Current Assembly (DCA) card at location $(BG_LOC).  The condition is $(COND).  The invalid value is $(BADVAL)."
  description="The Health Check analyzed the IO board at the specified location, and found an abnormal condition for a DCA card."
  service_action="If the card continues to have this error, run diagnostics on the IO board."
  relevant_diags="ioboard"
  details="COND, BADVAL"
  />

  <rasevent  id="0x0006100C"  component="MMCS"
  category="DCA"
  severity="WARN"
  message="Health Check detected an abnormal condition for the Direct Current Assembly (DCA) card at location $(BG_LOC).  The condition is related to $(COND).  The invalid value is $(BADVAL)."
  description="The Health Check analyzed the node board at the specified location, and found an abnormal condition for a DCA card."
  service_action="If the card continues to have this error, run diagnostics on the node board."
  relevant_diags="nodeboard"
  details="COND, BADVAL"
  />

  <rasevent  id="0x0006100D"  component="MMCS"
  category="Optical_Module"
  severity="WARN"
  message="Health Check detected an abnormal condition for the optical module at location $(BG_LOC).  The condition is related to $(COND)."
  description="The Health Check analyzed the IO board at the specified location, and found an abnormal condition for an optical module."
  service_action="If the card continues to have this error, run diagnostics on the IO board."
  relevant_diags="ioboard"
  details="COND"
  />

  <rasevent  id="0x0006100E"  component="MMCS"
  category="Optical_Module"
  severity="WARN"
  message="Health Check detected an abnormal condition for the optical module at location $(BG_LOC).  The condition is related to $(COND)."
  description="The Health Check analyzed the node board at the specified location, and found an abnormal condition for an optical module."
  service_action="If the card continues to have this error, run diagnostics on the node board."
  relevant_diags="nodeboard"
  details="COND"
  />

  <rasevent  id="0x0006100F"  component="MMCS"
  category="AC_TO_DC_PWR"
  severity="WARN"
  message="Health Check detected an abnormal condition for the bulk power module at location $(BG_LOC).  The condition is related to $(COND).  The invalid value is $(BADVAL)."
  description="The Health Check analyzed the bulk power module at the specified location, and found an abnormal condition."
  service_action="If the bulk power module continues to have this error, look at the LEDs on the modules to determine if there is a failure."
  relevant_diags=""
  details="COND, BADVAL"
  />

  <rasevent  id="0x00061010"  component="MMCS"
  category="Node_Board"
  severity="WARN"
  message="Health Check detected an incorrect clock frequency $(FREQ) on the node board at location $(BG_LOC)."
  description="The Health Check analyzed the node board at the specified location, and found a clock frequency that was outside the expected range."
  service_action="If the card continues to have this error, run diagnostics on the node board. The problem may also be originating from the master clock card."
  relevant_diags="nodeboard"
  details="FREQ"
  />

  <rasevent  id="0x00061011"  component="MMCS"
  category="Node_Board"
  severity="WARN"
  message="Health Check detected an abnormal status flag set for the node board at location $(BG_LOC).  The status flag is for $(COMP)."
  description="The Health Check analyzed the node board at the specified location, and found a status flag set for an abnormal condition."
  service_action="If the card continues to have this error, run diagnostics on the node board."
  relevant_diags="nodeboard"
  details="COMP"
  />

  <rasevent  id="0x00061012"  component="MMCS"
  category="AC_TO_DC_PWR"
  severity="FATAL"
  message="Health Check detected multiple failed bulk power modules in an enclosure.  Hardware at location $(BG_LOC) is being marked in error."
  description="The Health Check analyzed the bulk power modules in the midplane, and found multiple failures. Individual RAS events have been sent for each condition.  Hardware has been marked in Error to prevent further use.  Any running jobs have been killed and blocks freed."
  service_action="If the bulk power modules continue to have this error, replace the failed modules."
  relevant_diags=""
  control_action="BOARD_IN_ERROR,END_JOB,FREE_COMPUTE_BLOCK"
  />

  <rasevent  id="0x00061013"  component="MMCS"
  category="AC_TO_DC_PWR"
  severity="FATAL"
  message="Health Check detected multiple failed bulk power modules in an enclosure.  Hardware at location $(BG_LOC) is being marked in error."
  description="The Health Check analyzed the bulk power modules in the midplane, and found multiple failures. Individual RAS events have been sent for each condition.  Hardware has been marked in Error to prevent further use."
  service_action="If the bulk power modules continue to have this error, replace the failed modules."
  relevant_diags=""
  control_action="BOARD_IN_ERROR,END_JOB,FREE_COMPUTE_BLOCK"
  />

 <rasevent  id="0x00061014"  component="MMCS"
  category="Coolant_Monitor"
  severity="FATAL"
  message="Health Check detected the coolant monitor connected to the service card at location $(BG_LOC) has been shut-off: $(COND)"
  description="The Health Check analyzed the coolant monitor at the specified location, and received an indication that its shut-off register has latched."
  service_action="Repair the coolant water problem, recover the rack using a Service Action."
  relevant_diags=""
  details="COND"
  threshold_count="1"
 />

  <rasevent  id="0x00061015"  component="MMCS"
  category="BQC"
  severity="WARN"
  message="Health Check detected an overtemp condition on the compute node at location $(BG_LOC).  The temperature $(ACTUAL) is above the expected maximum temperature of $(EXP). "
  description="The Health Check analyzed the node at the specified location, and found a temperature that was outside the expected range."
  service_action="It's possible the compute is not properly seated, the thermal interface material (TIM) is missing or was not properly applied, the TIM needs replacement, or the clear plastic TIM protector was not removed prior to installing the compute. Inspect the compute node and if no obvious reason for the high temperatures is noted, replace the compute node."
  relevant_diags="nodeboard"
  details="ACTUAL, EXP"
  />

*/

