/* begin_generated_IBM_copyright_prolog                             */
/*                                                                  */
/* This is an automatically generated copyright prolog.             */
/* After initializing,  DO NOT MODIFY OR MOVE                       */
/* ================================================================ */
/*                                                                  */
/* Licensed Materials - Property of IBM                             */
/*                                                                  */
/* Blue Gene/Q                                                      */
/*                                                                  */
/* (C) Copyright IBM Corp.  2010, 2011                              */
/*                                                                  */
/* US Government Users Restricted Rights -                          */
/* Use, duplication or disclosure restricted                        */
/* by GSA ADP Schedule Contract with IBM Corp.                      */
/*                                                                  */
/* This software is available to you under the                      */
/* Eclipse Public License (EPL).                                    */
/*                                                                  */
/* ================================================================ */
/*                                                                  */
/* end_generated_IBM_copyright_prolog                               */

/*! \page sampleClients Sample Clients
 *

Sample clients for accessing BGWS:

- bgws_session -- start, end, and list sessions
- listblocks -- list blocks or get block details
- createblock -- create a block
- deleteblock -- delete a block

These programs are NOT installed.

All of these programs take a -h option that describes the parameters.


\section Sessions

bgws_session starts a session and stores the session ID in a file.
By default, the file is ~/.bgws_session.
The session ID file name can be overridden using the -s option,
or use -s "" to not use a session file.
The other commands read the session ID from the session file.


\section errors Common Errors


\subsection sampleClientInvalidCert SSL certificate problem

You get this error if the server's certificate is not valid according to the CA:

<pre>
./bgws_session: error, curl operation failed, SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
</pre>

To fix, make sure you followed \ref sampleClientSetup "the client setup steps".


\section sampleClientSetup Setup

\note
This is the recommended default setup.
You may want to use a different setup if you want to use a different certificate for your web server
(for example, one generated by a commercial certificate authority).

Every system automatically gets a self-signed certificate when it's installed.
By default, Apache is configured to present the system certificate
when a client connects to the server using https.
Clients should validate the certificate that the server presented against the certificates that it trusts
and not continue if it doesn't trust the certificate.
Clients typically do not trust self-signed certificates,
so the BGWS command-line utilities must be configured to trust the system certificate.

The system's self-signed certificate is stored in /etc/pki/tls/certs/localhost.crt .
It should be copied to /bgsys/local/etc/security/bgws_client_ca.cert .

<pre>
# cp /etc/pki/tls/certs/localhost.crt /bgsys/local/etc/security/bgws_client_ca.cert
# chown root:root /bgsys/local/etc/security/bgws_client_ca.cert
# chmod 664 /bgsys/local/etc/security/bgws_client_ca.cert
</pre>

The default bg.properties references the bgws_client_ca.cert so
shouldn't have to be changed.

The <b>base_url</b> in the <b>bgws.clients</b> section in the bg.properties file
should be changed to the real hostname of the service node.


\section sampleClientConfiguration Configuration

The sample clients read configuration options from the BG configuration file (bg.properties).

I removed the client settings from the bg.properties template file because the sample clients aren't shipped.
The bgws.clients section must be manually added to the bg.properties file before using the clients.

They read values from the <b>bgws.clients</b> section.

<pre>
[bgws.clients]
    # Settings for the BGWS command-line utilities

base_url = https://localhost/bg
    # base URL to BGWS, defaults to https://localhost/bg

certificate_authority_certificate = /bgsys/local/etc/security/bgws_client_ca.crt
    # Certificate authority certificate file.
    # If not set, no CA certificate is used.
</pre>

 */
