#!/usr/bin/perl -w

use strict;

my $line;
while (defined($line = <STDIN>)) {
    my $prt = 0;
    if    ($line =~ m/^\s*$/o)   { }
    elsif ($line =~ m/^submit/o) { $prt = 1; }
    elsif ($line =~ m/^---/o) { $prt = 1; }
    elsif ($line =~ m/runjob\.sh/o) { $prt = 1; }
    elsif ($line =~ m/subjob\.sh/o) { $prt = 1; }
    elsif ($line =~ m/runfctest\.sh/o) { $prt = 1; }
    elsif ($line =~ m/^\{/o)    { $prt = 1; }
    elsif ($line =~ m/^OK/o)    { $prt = 1; }
    elsif ($line =~ m/^FAIL/o)    { $prt = 1; }
    elsif ($line =~ m/^\d+\-\d+\-\d+\s+\d+:\d+:\d+\.\d+\s+\(ERROR\)/o) { $prt = 1; }
    
    if ($prt) {
        # print $line;
        if ($line =~ m/^(\{\S+?\})(\d+):(\d+)(.*)/o) {
            my $node = $1;
            my $core = $2;
            my $thd = $3;
            my $rest = $4;
            chomp $rest;
            if ($core =~ m/^\d$/o) { $core = "0$core"; }
            if ($thd  =~ m/^\d$/o) { $thd = "0$thd"; }
            $line = "$node$core:$thd$rest\n";
        }
        print $line;        
    }
}
