#!/usr/bin/perl -w

use strict;

my $noRank = "99999999";
my %sorted;

my $lastLine = 0;
if ($ARGV[0] eq "-last") {
    $lastLine = 1;
}

my $line;
while (defined($line = <STDIN>)) {
    if ($line =~ m/^(?:(?:stdout)|(?:stderr))\[(\d+)\]:\s+(?:(?:BGPM_TRACE)|(?:UPCI_TRACE))\s+\((\d+)\)/ox) {
        my $rank = sprintf("%02d%02d", $1, $2);
        push @{$sorted{$rank}}, $line;
    }
    elsif ($line =~ m/^(?:(?:stdout)|(?:stderr))\[(\d+)\]:\s+thd\S*\s+(\d+)/oix) {
        my $rank = sprintf("%02d%02d", $1, $2);
        push @{$sorted{$rank}}, $line;
    }
    elsif ($line =~ m/^(?:(?:stdout)|(?:stderr))\[(\d+)\]:\s+(\d+)/ox) {
        my $rank = sprintf("%02d%02d", $1, $2);
        push @{$sorted{$rank}}, $line;
    }
    elsif ($line =~ m/^\{(\d+)\}\.(\d+)\.(\d+)\:/o) {
        my $rank = sprintf("%d%02d%02d", $1, $2, $3);
        #print "$rank\n";
        push @{$sorted{$rank}}, $line;
    }
    elsif ($line =~ m/^\{(\S+)\}(\d+):(\d+)/o) {
        my $rank = sprintf("%s%02d%02d", $1, $2, $3);
        $rank =~ s/\D//g;
        #print "$rank\n";
        push @{$sorted{$rank}}, $line;
    }
    elsif ($line =~ m/^(?:(?:BGPM_TRACE)|(?:UPCI_TRACE))\s+\((\d+)\)/ox) {
        my $rank = sprintf("%02d", $1);
        $rank =~ s/\D//g;
        #print "$rank\n";
        push @{$sorted{$rank}}, $line;
    }
    elsif ($line =~ m/^(?:(?:stdout)|(?:stderr))\[(\d+)\]:/ox) {
        my $rank = sprintf("%02d00", $1);
        push @{$sorted{$rank}}, $line;
    }
    else {
        push @{$sorted{$noRank}}, $line;
    }
}

 

my @ranks = sort { $a <=> $b } keys(%sorted);

my $lastPrintLine = "";
foreach my $rank (@ranks) {
    foreach $line (@{$sorted{$rank}}) {
         if (!$lastLine) {
             print $line;
         }
         else {
             $lastPrintLine = $line;
         }
    }
    if ($lastLine) {
        print $lastPrintLine;
    }
    else {
        print "\n\n";
    }
}
